#!/usr/bin/env bash

# configure rapsberry version
# - "rpi_zero_x86" | Raspberry 1/Zero/CM 32bit
# - "rpi_3_x86" | Raspberry (3, 3A+, 3B+) 32bit
# - "rpi_3_x64" | Raspberry (3, 3A+, 3B+) 64bit
#
CONF_TARGET_DEVICE="rpi_3_x64"

# use standard img, not cpio wrapped
CONF_IMAGE_TYPE="img"

# use LZO compression - LZ4 (default) is not supported within the official kernel
CONF_SQUASHFS_ARGS=(-comp lzo)

# official firmware + kernel
# kernel type (debian or official)
RASPBERRY_KERNEL_TYPE="official"

# kernel+firmware releases of the "official" image
RASPBERRY_KERNEL_VERSION="5.4.51"
RASPBERRY_FIRMWARE_RELEASE="1.20200902"

# no manual config beyond this line
# ----------------------------------------------

# target architecture
CONF_ARCH=

case ${CONF_TARGET_DEVICE} in
    rpi_zero_x86)
        CONF_ARCH=armel
        ;;
    rpi_3_x86)
        CONF_ARCH=armhf
        ;;
    rpi_3_x64)
        CONF_ARCH=arm64
        ;;
    *)
        echo "invalid target device $ARG"
        exit 1
        ;;
esac

export CONF_TARGET_DEVICE
export CONF_ARCH
export RASPBERRY_KERNEL_VERSION
export RASPBERRY_FIRMWARE_RELEASE
export RASPBERRY_KERNEL_TYPE

# info
echo "[raspberry] target architecture $CONF_ARCH on $CONF_TARGET_DEVICE"

# using official kernel ?
if [ "$RASPBERRY_KERNEL_TYPE" = "official" ]; then
    echo "[raspberry] official firmware release $RASPBERRY_FIRMWARE_RELEASE with kernel $RASPBERRY_KERNEL_VERSION"
fi